(* Language Grammar *)

<S> = exp_Arithmetic
expression = (exp_Arithmetic | exp_Function)*
exp_Function = #'fun_[a-zA-Z]+\(\)'
exp_Arithmetic = sym_Number <whitespace> sym_Operator <whitespace> sym_Number

whitespace = #'[\s]?'

(* symbols *)
sym_Operator = #'[\+\-\*]'
sym_Number = #'[1-9]+'

