(* Language Grammar *)

<S> = exp_Arithmetic
<exp_Arithmetic> = sym_Number <whitespace> sym_Operator <whitespace> sym_Number

whitespace = #'[\s]?'

(* symbols *)
sym_Operator = #'[\+\-\*]'
sym_Number = #'[1-9]+'

