(* Language Grammar *)

<S> = expression
expression = ((exp_Arithmetic | exp_Function) <';'> <#'[\s]?'>)*
exp_Function = #'fun_[a-zA-Z]+\(\)'
exp_Arithmetic = sym_Number <whitespace> sym_Operator <whitespace> sym_Number

whitespace = #'[\s]?'

(* symbols *)
sym_Operator = #'[\+\-\*]'
sym_Number = #'[1-9]+'

